# build the project
tasks:
  - name: Setup maven
    init: mvn install
  - name: Setup Mysql  
    init: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=Pass123$ -d mysql:5.7 && sudo apt install maven && docker exec -it some-mysql  mysql -uroot -pPass123$
  - name: Open Readme
    init: gp open README.md
        
ports:
  - port: 35729
    onOpen: ignore     
